<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GKvocab [
<!ELEMENT GKvocab (vocab_entry*)>

<!-- Voabu;ary Entries consist of ...  -->
<!ELEMENT vocab_entry (ent_seq, kanji, furigana, jlpt, level,  pos,  definition+, notes+, tags+ )>

<!ELEMENT ent_seq (#PCDATA)>
	<!-- A unique numeric sequence number for each vocab entry -->

<!ELEMENT kanji (#PCDATA)>
	<!-- The vocabulary entry text containing kanji characters -->

<!ELEMENT furigana (#PCDATA)>
	<!-- Vocabulary entry in furigana -->

<!ELEMENT jlpt (#PCDATA)>
	<!--  JLPT Level N5, N4, N3, N2, N1, N1+ -->

<!ELEMENT level (#PCDATA)>
	<!--  Sublevel within the JLPT level -->

<!ELEMENT pos (#PCDATA)>
	<!--  Part of Speech -->

<!ELEMENT definition (#PCDATA)>
	<!-- Main definition -->

<!ELEMENT notes (#PCDATA)>
	<!-- Helpful notes about hte vocabulary entry-->

<!ELEMENT tags (#PCDATA)>
	<!-- Tags to further classify the vocabulary entry -->
]>


<!-- GKvocab created: 2019-2-20 -->
<GKvocab>

<vocab_entry>
<ent_seq>20190210000</ent_seq>
<jlpt>2</jlpt>
<level>1</level>
<kanji></kanji>
<furigana>あいかわらず</furigana>
<definition>as ever</definition>
<definition>as usual</definition>
<definition>the same</definition>
</vocab_entry>

<vocab_entry>
<ent_seq>20190210001</ent_seq>
<jlpt>2</jlpt>
<level>1</level>
<kanji></kanji>
<furigana>アイディア</furigana>
<definition>idea</definition>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021000</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>遭う</kanji>
<furigana>あう</furigana>
<definition>to meet</definition>
<definition>to encounter (undesirable nuance)</definition>
<dict_seq>1198180</dict_seq>
<pos>Verb5_u</pos>
<pos>Verb: Intransitive</pos>
<s_inf>逢う is often used for close friends, etc. and may be associated with drama or pathos; 遭う may have an undesirable nuance</s_inf>
<s_inf>esp. 遭う when in kanji</s_inf>
<misc>word usually written using kana alone</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021001</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>扇ぐ</kanji>
<furigana>あおぐ</furigana>
<definition>to fan</definition>
<definition>to flap</definition>
<dict_seq>1609000</dict_seq>
<pos>Verb_5_gu</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021002</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>青白い</kanji>
<furigana>あおじろい</furigana>
<definition>pale</definition>
<definition>pallid</definition>
<dict_seq>1381760</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021003</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>明き</kanji>
<furigana>あき</furigana>
<definition>room</definition>
<definition>time to spare</definition>
<definition>emptiness</definition>
<dict_seq>1609010</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021004</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>飽くまで</kanji>
<furigana>あくまで</furigana>
<definition>to the end</definition>
<definition>to the last</definition>
<definition>stubbornly</definition>
<dict_seq>1518320</dict_seq>
<pos>Adverb</pos>
<misc>word usually written using kana alone</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021005</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>明け方</kanji>
<furigana>あけがた</furigana>
<definition>dawn</definition>
<dict_seq>1532300</dict_seq>
<pos>Adverbial Noun</pos>
<pos>Noun</pos>
<pos>temporal)</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021006</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>揚げる</kanji>
<furigana>あげる</furigana>
<definition>to lift</definition>
<definition>to fry</definition>
<dict_seq>1352320</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
<misc>word usually written using kana alone</misc>
<s_inf>usu. 挙げる</s_inf>
<misc>polite (teineigo) language</misc>
<pos>Verb: Intransitive</pos>
<pos>Auxiliary Verb</pos>
<s_inf>after the -te form of a verb</s_inf>
<s_inf>after the -masu stem of a verb</s_inf>
<s_inf>after the -masu stem of a humble verb to increase the level of humility</s_inf>
<misc>humble (kenjougo) language</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021007</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>挙げる</kanji>
<furigana>あげる</furigana>
<definition>to raise</definition>
<definition>to fly</definition>
<dict_seq>1352320</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
<misc>word usually written using kana alone</misc>
<s_inf>usu. 挙げる</s_inf>
<misc>polite (teineigo) language</misc>
<pos>Verb: Intransitive</pos>
<pos>Auxiliary Verb</pos>
<s_inf>after the -te form of a verb</s_inf>
<s_inf>after the -masu stem of a verb</s_inf>
<s_inf>after the -masu stem of a humble verb to increase the level of humility</s_inf>
<misc>humble (kenjougo) language</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021008</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>憧れる</kanji>
<furigana>あこがれる</furigana>
<definition>to long for</definition>
<definition>to yearn after</definition>
<definition>to admire</definition>
<dict_seq>1453810</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021009</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>足跡</kanji>
<furigana>あしあと</furigana>
<definition>footprints</definition>
<dict_seq>1581330</dict_seq>
<pos>Noun</pos>
<field>computer terminology</field>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021010</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>味わう</kanji>
<furigana>あじわう</furigana>
<definition>to taste</definition>
<definition>to savor</definition>
<definition>to relish</definition>
<dict_seq>1527010</dict_seq>
<pos>Verb5_u</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021011</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>預かる</kanji>
<furigana>あずかる</furigana>
<definition>to keep in custody</definition>
<definition>to receive on deposit</definition>
<definition>to take charge of</definition>
<dict_seq>1544970</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021012</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>暖まる</kanji>
<furigana>あたたまる</furigana>
<definition>to warm up</definition>
<definition>to get warm</definition>
<dict_seq>1586430</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021013</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>暖める</kanji>
<furigana>あたためる</furigana>
<definition>to warm</definition>
<definition>to heat</definition>
<dict_seq>1586440</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021014</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>厚かましい</kanji>
<furigana>あつかましい</furigana>
<definition>impudent</definition>
<definition>shameless</definition>
<definition>brazen</definition>
<dict_seq>1275330</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021015</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>圧縮</kanji>
<furigana>あっしゅく</furigana>
<definition>compression</definition>
<definition>condensation</definition>
<definition>pressure</definition>
<dict_seq>1153080</dict_seq>
<pos>Noun</pos>
<pos>takes -suru</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021016</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>宛名</kanji>
<furigana>あてな</furigana>
<definition>address</definition>
<definition>direction</definition>
<dict_seq>1586520</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021017</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>暴れる</kanji>
<furigana>あばれる</furigana>
<definition>to act violently</definition>
<definition>to rage</definition>
<definition>to struggle</definition>
<definition>to be riotous</definition>
<dict_seq>1519340</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021018</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>脂</kanji>
<furigana>あぶら</furigana>
<definition>fat</definition>
<definition>tallow</definition>
<definition>lard</definition>
<dict_seq>1311750</dict_seq>
<pos>Noun</pos>
<dict_seq>1311760</dict_seq>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021019</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>雨戸</kanji>
<furigana>あまど</furigana>
<definition>sliding storm door</definition>
<dict_seq>1171970</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021020</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>甘やかす</kanji>
<furigana>あまやかす</furigana>
<definition>to pamper</definition>
<definition>to spoil</definition>
<dict_seq>1213470</dict_seq>
<pos>Verb_5_su</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021021</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>余る</kanji>
<furigana>あまる</furigana>
<definition>to remain</definition>
<definition>to be left over</definition>
<definition>to be in excess</definition>
<definition>to be too many</definition>
<dict_seq>1543910</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021022</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>編物</kanji>
<furigana>あみもの</furigana>
<definition>knitting</definition>
<definition>web</definition>
<dict_seq>1586670</dict_seq>
<pos>Noun</pos>
<pos>takes -no</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021023</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>編む</kanji>
<furigana>あむ</furigana>
<definition>to knit</definition>
<dict_seq>1511950</dict_seq>
<pos>Verb_5_mu</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021024</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>危うい</kanji>
<furigana>あやうい</furigana>
<definition>dangerous</definition>
<definition>critical</definition>
<definition>grave</definition>
<dict_seq>1218360</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021025</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>怪しい</kanji>
<furigana>あやしい</furigana>
<definition>suspicious</definition>
<definition>dubious</definition>
<definition>doubtful</definition>
<dict_seq>1586700</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021026</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>荒い</kanji>
<furigana>あらい</furigana>
<definition>rough</definition>
<definition>rude</definition>
<definition>wild</definition>
<dict_seq>1281450</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021027</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>粗い</kanji>
<furigana>あらい</furigana>
<definition>coarse</definition>
<definition>rough</definition>
<dict_seq>1396910</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021028</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>争う</kanji>
<furigana>あらそう</furigana>
<definition>to dispute</definition>
<definition>to argue</definition>
<definition>to be at variance</definition>
<definition>to compete</definition>
<dict_seq>1400620</dict_seq>
<pos>Verb5_u</pos>
<pos>Verb: Intransitive</pos>
<dict_seq>2261110</dict_seq>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021029</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>改めて</kanji>
<furigana>あらためて</furigana>
<definition>another time</definition>
<definition>again</definition>
<definition>over again</definition>
<definition>anew</definition>
<definition>formally</definition>
<dict_seq>1200740</dict_seq>
<pos>Adverb</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021030</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>改める</kanji>
<furigana>あらためる</furigana>
<definition>to change</definition>
<definition>to alter</definition>
<definition>to reform</definition>
<definition>to revise</definition>
<dict_seq>1200750</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021031</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>著す</kanji>
<furigana>あらわす</furigana>
<definition>to write</definition>
<definition>to publish</definition>
<dict_seq>1427080</dict_seq>
<pos>Verb_5_su</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021032</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>有難い</kanji>
<furigana>ありがたい</furigana>
<definition>grateful</definition>
<definition>thankful</definition>
<definition>welcome</definition>
<definition>appreciated</definition>
<definition>evoking gratitude</definition>
<dict_seq>1541560</dict_seq>
<pos>Adjective</pos>
<misc>word usually written using kana alone</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021033</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>在る</kanji>
<furigana>ある</furigana>
<definition>to live</definition>
<definition>to be</definition>
<dict_seq>1296400</dict_seq>
<pos>Verb_5_ru</pos>
<pos>irregular</pos>
<pos>Verb: Intransitive</pos>
<misc>word usually written using kana alone</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021034</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>安易</kanji>
<furigana>あんい</furigana>
<definition>easy-going</definition>
<dict_seq>1153720</dict_seq>
<pos>Adj-Noun</pos>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021035</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>案外</kanji>
<furigana>あんがい</furigana>
<definition>unexpectedly</definition>
<dict_seq>1154820</dict_seq>
<pos>Adj-Noun</pos>
<pos>Adverbial Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021036</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>言い出す</kanji>
<furigana>いいだす</furigana>
<definition>to start talking</definition>
<definition>to speak</definition>
<definition>to tell</definition>
<definition>to propose</definition>
<definition>to suggest</definition>
<definition>to break the ice</definition>
<dict_seq>1264080</dict_seq>
<pos>Verb_5_su</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021037</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>言い付ける</kanji>
<furigana>いいつける</furigana>
<definition>to tell</definition>
<definition>to tell on (someone)</definition>
<definition>to order</definition>
<dict_seq>1264230</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021038</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>意義</kanji>
<furigana>いぎ</furigana>
<definition>meaning</definition>
<definition>significance</definition>
<dict_seq>1156520</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021039</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>生き生き</kanji>
<furigana>いきいき</furigana>
<definition>vividly</definition>
<definition>lively</definition>
<dict_seq>1609130</dict_seq>
<pos>Adverb</pos>
<pos>takes -to</pos>
<pos>Noun</pos>
<pos>takes -suru</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021040</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>育児</kanji>
<furigana>いくじ</furigana>
<definition>childcare</definition>
<definition>nursing</definition>
<definition>upbringing</definition>
<dict_seq>1160630</dict_seq>
<pos>Noun</pos>
<pos>takes -suru</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021041</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>幾分</kanji>
<furigana>いくぶん</furigana>
<definition>somewhat</definition>
<dict_seq>1220060</dict_seq>
<pos>Adverb</pos>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021042</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>生け花</kanji>
<furigana>いけばな</furigana>
<definition>flower arrangement</definition>
<dict_seq>1587180</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021043</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>以後</kanji>
<furigana>いご</furigana>
<definition>after this</definition>
<definition>from now on</definition>
<definition>hereafter</definition>
<definition>thereafter</definition>
<dict_seq>1155100</dict_seq>
<pos>Adverbial Noun</pos>
<pos>Noun</pos>
<pos>temporal)</pos>
<s_inf>esp. after あれ, それ</s_inf>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021044</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>以降</kanji>
<furigana>いこう</furigana>
<definition>on and after</definition>
<definition>hereafter</definition>
<definition>thereafter</definition>
<dict_seq>1155110</dict_seq>
<pos>Adverbial Noun</pos>
<pos>Noun</pos>
<pos>temporal)</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021045</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>勇ましい</kanji>
<furigana>いさましい</furigana>
<definition>brave</definition>
<definition>valiant</definition>
<definition>gallant</definition>
<definition>courageous</definition>
<dict_seq>1539660</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021046</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>衣食住</kanji>
<furigana>いしょくじゅう</furigana>
<definition>necessities of life (food, clothing, etc.)</definition>
<dict_seq>1158780</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021047</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>意地悪</kanji>
<furigana>いじわる</furigana>
<definition>malicious</definition>
<definition>ill-tempered</definition>
<definition>unkind</definition>
<dict_seq>1156740</dict_seq>
<pos>Adj-Noun</pos>
<pos>Noun</pos>
<pos>takes -suru</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021048</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一応</kanji>
<furigana>いちおう</furigana>
<definition>once</definition>
<definition>tentatively</definition>
<definition>in outline</definition>
<definition>for the time being</definition>
<dict_seq>1161170</dict_seq>
<pos>Adverb</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021049</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一段と</kanji>
<furigana>いちだんと</furigana>
<definition>greater</definition>
<definition>more</definition>
<definition>further</definition>
<definition>still more</definition>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021050</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一流</kanji>
<furigana>いちりゅう</furigana>
<definition>first class</definition>
<definition>top grade</definition>
<definition>foremost</definition>
<definition>top-notch</definition>
<dict_seq>1167270</dict_seq>
<pos>Noun</pos>
<pos>takes -no</pos>
<s_inf>also written as 一旒</s_inf>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021051</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>佚</kanji>
<furigana>いつ</furigana>
<definition>be lost</definition>
<definition>peace</definition>
<definition>hide</definition>
<definition>mistake</definition>
<definition>beautiful</definition>
<definition>in turn</definition>
<dict_seq>1585390</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021052</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一昨日</kanji>
<furigana>いっさくじつ</furigana>
<definition>day before yesterday</definition>
<dict_seq>1576050</dict_seq>
<pos>Adverbial Noun</pos>
<pos>Noun</pos>
<pos>temporal)</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021053</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一昨年</kanji>
<furigana>いっさくねん</furigana>
<definition>year before last</definition>
<dict_seq>1576060</dict_seq>
<pos>Adverbial Noun</pos>
<pos>Noun</pos>
<pos>temporal)</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021054</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一斉</kanji>
<furigana>いっせい</furigana>
<definition>simultaneous</definition>
<definition>all at once</definition>
<dict_seq>1164040</dict_seq>
<pos>Adverbial Noun</pos>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021055</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一旦</kanji>
<furigana>いったん</furigana>
<definition>once</definition>
<definition>for a moment</definition>
<definition>one morning</definition>
<definition>temporarily</definition>
<dict_seq>1164650</dict_seq>
<pos>Adverb</pos>
<misc>word usually written using kana alone</misc>
<pos>Noun</pos>
<misc>archaism</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021056</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>一定</kanji>
<furigana>いってい</furigana>
<definition>fixed</definition>
<definition>settled</definition>
<definition>definite</definition>
<dict_seq>1164950</dict_seq>
<pos>Noun</pos>
<pos>takes -no</pos>
<pos>takes -suru</pos>
<pos>Adj-Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021057</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>移転</kanji>
<furigana>いてん</furigana>
<definition>moving</definition>
<definition>transfer</definition>
<definition>demise</definition>
<dict_seq>1158390</dict_seq>
<pos>Noun</pos>
<pos>takes -suru</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021058</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>井戸</kanji>
<furigana>いど</furigana>
<definition>water well</definition>
<dict_seq>1160330</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021059</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>緯度</kanji>
<furigana>いど</furigana>
<definition>latitude (nav.)</definition>
<dict_seq>1158490</dict_seq>
<pos>Noun</pos>
<pos>takes -no</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021060</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>従姉妹</kanji>
<furigana>いとこ</furigana>
<definition>cousin (female)</definition>
<dict_seq>1335310</dict_seq>
<pos>Noun</pos>
<misc>word usually written using kana alone</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021061</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>威張る</kanji>
<furigana>いばる</furigana>
<definition>to be proud</definition>
<definition>to swagger</definition>
<dict_seq>1156320</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021062</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>嫌がる</kanji>
<furigana>いやがる</furigana>
<definition>to hate</definition>
<definition>to dislike</definition>
<dict_seq>1609260</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021063</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>煎る</kanji>
<furigana>いる</furigana>
<definition>to parch</definition>
<definition>to fry</definition>
<dict_seq>1391500</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021064</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>入れ物</kanji>
<furigana>いれもの</furigana>
<definition>container</definition>
<definition>case</definition>
<definition>receptacle</definition>
<dict_seq>1587840</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021065</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>引力</kanji>
<furigana>いんりょく</furigana>
<definition>gravity</definition>
<dict_seq>1169720</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021066</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>植木</kanji>
<furigana>うえき</furigana>
<definition>garden shrubs</definition>
<definition>trees</definition>
<definition>potted plant</definition>
<dict_seq>1587970</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021067</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>飢える</kanji>
<furigana>うえる</furigana>
<definition>to starve</definition>
<dict_seq>1224080</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021068</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>浮ぶ</kanji>
<furigana>うかぶ</furigana>
<definition>to float</definition>
<definition>to rise to surface</definition>
<definition>to come to mind</definition>
<dict_seq>1497430</dict_seq>
<pos>Verb_5_bu</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021069</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>浮かべる</kanji>
<furigana>うかべる</furigana>
<definition>to float</definition>
<definition>to express</definition>
<definition>to look (sad, glad)</definition>
<dict_seq>1497360</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021070</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>浮く</kanji>
<furigana>うく</furigana>
<definition>to float</definition>
<definition>to become merry</definition>
<definition>to become loose</definition>
<dict_seq>1497420</dict_seq>
<pos>Verb_5_ku</pos>
<pos>Verb: Intransitive</pos>
<misc>colloquialism</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021071</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>承る</kanji>
<furigana>うけたまわる</furigana>
<definition>(hum) to hear</definition>
<definition>to be told</definition>
<definition>to know</definition>
<dict_seq>1349440</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Transitive</pos>
<misc>humble (kenjougo) language</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021072</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>受取</kanji>
<furigana>うけとり</furigana>
<definition>receipt</definition>
<dict_seq>1329770</dict_seq>
<pos>Noun</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021073</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>受け持つ</kanji>
<furigana>うけもつ</furigana>
<definition>to take (be in) charge of</definition>
<dict_seq>1329640</dict_seq>
<pos>Verb_5_tsu</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021074</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>薄暗い</kanji>
<furigana>うすぐらい</furigana>
<definition>dim</definition>
<definition>gloomy</definition>
<dict_seq>1475530</dict_seq>
<pos>Adjective</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021075</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>薄める</kanji>
<furigana>うすめる</furigana>
<definition>to dilute</definition>
<definition>to water down</definition>
<dict_seq>1475500</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021076</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>打合せ</kanji>
<furigana>うちあわせ</furigana>
<definition>business meeting</definition>
<definition>previous arrangement</definition>
<definition>appointment</definition>
<dict_seq>1588140</dict_seq>
<pos>Noun</pos>
<pos>takes -suru</pos>
<misc>archaism</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021077</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>打ち消す</kanji>
<furigana>うちけす</furigana>
<definition>to deny</definition>
<definition>to negate</definition>
<definition>to contradict</definition>
<dict_seq>1609310</dict_seq>
<pos>Verb_5_su</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021078</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>討つ</kanji>
<furigana>うつ</furigana>
<definition>to attack</definition>
<definition>to avenge</definition>
<dict_seq>1253570</dict_seq>
<pos>Verb_5_tsu</pos>
<s_inf>usu. 撃つ</s_inf>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021079</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>映す</kanji>
<furigana>うつす</furigana>
<definition>to project</definition>
<definition>to reflect</definition>
<definition>to cast (shadow)</definition>
<dict_seq>1588330</dict_seq>
<pos>Verb_5_su</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021080</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>写る</kanji>
<furigana>うつる</furigana>
<definition>to be photographed</definition>
<definition>to be projected</definition>
<dict_seq>1321820</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021081</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>映る</kanji>
<furigana>うつる</furigana>
<definition>to be reflected</definition>
<definition>to harmonize with</definition>
<definition>to come out (photo)</definition>
<dict_seq>1173710</dict_seq>
<pos>Verb_5_ru</pos>
<pos>Verb: Intransitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021082</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>有無</kanji>
<furigana>うむ</furigana>
<definition>yes or no</definition>
<definition>existence</definition>
<definition>flag indicator (comp)</definition>
<definition>presence or absence marker</definition>
<dict_seq>1541610</dict_seq>
<pos>Noun</pos>
<field>computer terminology</field>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021083</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>埋める</kanji>
<furigana>うめる</furigana>
<definition>to bury</definition>
<definition>to fill up</definition>
<definition>to fill (a seat, a vacant position)</definition>
<dict_seq>1524490</dict_seq>
<pos>Verb_1</pos>
<pos>Verb: Transitive</pos>
<dict_seq>1524500</dict_seq>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021084</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>敬う</kanji>
<furigana>うやまう</furigana>
<definition>to show respect</definition>
<definition>to honour</definition>
<dict_seq>1250700</dict_seq>
<pos>Verb5_u</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021085</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>裏返す</kanji>
<furigana>うらがえす</furigana>
<definition>to turn inside out</definition>
<definition>to turn (something) over</definition>
<dict_seq>1550630</dict_seq>
<pos>Verb_5_su</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021086</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>裏口</kanji>
<furigana>うらぐち</furigana>
<definition>backdoor</definition>
<definition>rear entrance</definition>
<dict_seq>1550270</dict_seq>
<pos>Noun</pos>
<pos>takes -no</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021087</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>占う</kanji>
<furigana>うらなう</furigana>
<definition>to forecast</definition>
<definition>to predict</definition>
<dict_seq>1389430</dict_seq>
<pos>Verb5_u</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021088</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>恨み</kanji>
<furigana>うらみ</furigana>
<definition>resentment</definition>
<dict_seq>1289740</dict_seq>
<pos>Noun</pos>
<s_inf>esp. 憾み</s_inf>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021089</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>恨む</kanji>
<furigana>うらむ</furigana>
<definition>to curse</definition>
<definition>to feel bitter</definition>
<dict_seq>1289780</dict_seq>
<pos>Verb_5_mu</pos>
<pos>Verb: Transitive</pos>
<s_inf>esp. 憾む</s_inf>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021090</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>羨ましい</kanji>
<furigana>うらやましい</furigana>
<definition>envious</definition>
<definition>enviable</definition>
<dict_seq>1391940</dict_seq>
<pos>Adjective</pos>
<misc>word usually written using kana alone</misc>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021091</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>羨む</kanji>
<furigana>うらやむ</furigana>
<definition>to envy</definition>
<dict_seq>1391950</dict_seq>
<pos>Verb_5_mu</pos>
<pos>Verb: Transitive</pos>
</vocab_entry>

<vocab_entry>
<ent_seq>2019021092</ent_seq>
<jlpt>2</jlpt>
<level></level>
<kanji>売上</kanji>