<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GKvocab [
<!ELEMENT GKvocab (vocab_entry*)>

<!-- Voabu;ary Entries consist of ...  -->
<!ELEMENT vocab_entry (ent_seq, dict_seq, kanji, furigana, jlpt, level,  pos+,  definition+, misc+, s_inf+ )>

<!ELEMENT ent_seq (#PCDATA)>
	<!-- A unique numeric sequence number for each vocab entry -->

<!ELEMENT kanji (#PCDATA)>
	<!-- The vocabulary entry text containing kanji characters -->

<!ELEMENT furigana (#PCDATA)>
	<!-- Vocabulary entry in furigana -->

<!ELEMENT jlpt (#PCDATA)>
	<!--  JLPT Level N5, N4, N3, N2, N1, N1+ -->

<!ELEMENT level (#PCDATA)>
	<!--  Sublevel within the JLPT level -->

<!ELEMENT pos (#PCDATA)>
	<!--  Part of Speech -->

<!ELEMENT definition (#PCDATA)>
	<!-- Main definition -->

<!ELEMENT misc (#PCDATA)>
	<!-- Helpful notes about hte vocabulary entry-->

<!ELEMENT s_inf (#PCDATA)>
	<!-- Tags to further classify the vocabulary entry -->
]>


<!-- GKvocab created: 2019-2-20 -->
<GKvocab>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>
<furigana>あ</furigana>
<tanos_def>Ah</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>ああ</furigana>	
<tanos_def>like that</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>間</kanji>	
<furigana>あいだ</furigana>	
<tanos_def>a space</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>合う</kanji>	
<furigana>あう</furigana>	
<tanos_def>to match</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>あかちゃん</furigana>	
<tanos_def>baby</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>上る</kanji>	
<furigana>あがる</furigana>	
<tanos_def>to rise</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>赤ん坊</kanji>	
<furigana>あかんぼう</furigana>	
<tanos_def>baby</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>空く</kanji>	
<furigana>あく</furigana>	
<tanos_def>to open, to become empty</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>あげる</furigana>	
<tanos_def>to give</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>浅い</kanji>	
<furigana>あさい</furigana>	
<tanos_def>shallow, superficial</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>味</kanji>	
<furigana>あじ</furigana>	
<tanos_def>flavour</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>明日</kanji>	
<furigana>あす・あした</furigana>	
<tanos_def>tomorrow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>遊び</kanji>	
<furigana>あそび</furigana>	
<tanos_def>play</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>集る</kanji>	
<furigana>あつまる</furigana>	
<tanos_def>to gather</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>集める</kanji>	
<furigana>あつめる</furigana>	
<tanos_def>to collect something</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>謝る</kanji>	
<furigana>あやまる</furigana>	
<tanos_def>to apologize</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>安心</kanji>	
<furigana>あんしん</furigana>	
<tanos_def>relief</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>安全</kanji>	
<furigana>あんぜん</furigana>	
<tanos_def>safety</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>あんな</furigana>	
<tanos_def>such</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>以下</kanji>	
<furigana>いか</furigana>	
<tanos_def>less than</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>以外</kanji>	
<furigana>いがい</furigana>	
<tanos_def>with the exception of</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>医学</kanji>	
<furigana>いがく</furigana>	
<tanos_def>medical science</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>生きる</kanji>	
<furigana>いきる</furigana>	
<tanos_def>to live</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>意見</kanji>	
<furigana>いけん</furigana>	
<tanos_def>opinion</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>石</kanji>	
<furigana>いし</furigana>	
<tanos_def>stone</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>いじめる</furigana>	
<tanos_def>to tease</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>以上</kanji>	
<furigana>いじょう</furigana>	
<tanos_def>more than, this is all</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>急ぐ</kanji>	
<furigana>いそぐ</furigana>	
<tanos_def>to hurry</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>致す</kanji>	
<furigana>いたす</furigana>	
<tanos_def>(humble) to do</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>一度</kanji>	
<furigana>いちど</furigana>	
<tanos_def>once</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>一生懸命</kanji>	
<furigana>いっしょうけんめい</furigana>	
<tanos_def>with utmost effort</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>いっぱい</furigana>	
<tanos_def>full</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>糸</kanji>	
<furigana>いと</furigana>	
<tanos_def>thread</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>以内</kanji>	
<furigana>いない</furigana>	
<tanos_def>within</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>田舎</kanji>	
<furigana>いなか</furigana>	
<tanos_def>countryside</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>祈る</kanji>	
<furigana>いのる</furigana>	
<tanos_def>to pray</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>いらっしゃる</furigana>	
<tanos_def>(respectful) to be, to come or to go</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>植える</kanji>	
<furigana>うえる</furigana>	
<tanos_def>to plant, to grow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>受付</kanji>	
<furigana>うけつけ</furigana>	
<tanos_def>receipt</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>受ける</kanji>	
<furigana>うける</furigana>	
<tanos_def>to take a lesson or test</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>動く</kanji>	
<furigana>うごく</furigana>	
<tanos_def>to move</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>うち</furigana>	
<tanos_def>within</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>打つ</kanji>	
<furigana>うつ</furigana>	
<tanos_def>to hit</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>美しい</kanji>	
<furigana>うつくしい</furigana>	
<tanos_def>beautiful</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>写す</kanji>	
<furigana>うつす</furigana>	
<tanos_def>to copy or photograph</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>移る</kanji>	
<furigana>うつる</furigana>	
<tanos_def>to move house or transfer</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>腕</kanji>	
<furigana>うで</furigana>	
<tanos_def>arm</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>裏</kanji>	
<furigana>うら</furigana>	
<tanos_def>reverse side</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>売り場</kanji>	
<furigana>うりば</furigana>	
<tanos_def>place where things are sold</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>うん</furigana>	
<tanos_def>(informal) yes</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>運転手</kanji>	
<furigana>うんてんしゅ</furigana>	
<tanos_def>driver</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>枝</kanji>	
<furigana>えだ</furigana>	
<tanos_def>branch, twig</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>選ぶ</kanji>	
<furigana>えらぶ</furigana>	
<tanos_def>to choose</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>遠慮</kanji>	
<furigana>えんりょ・する</furigana>	
<tanos_def>to be reserved, to be restrained</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>おいでになる</furigana>	
<tanos_def>(respectful) to be</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お祝い</kanji>	
<furigana>おいわい</furigana>	
<tanos_def>congratulation</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>おかげ</furigana>	
<tanos_def>owing to, thanks to</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>おかしい</furigana>	
<tanos_def>strange or funny</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>億</kanji>	
<furigana>おく</furigana>	
<tanos_def>one hundred million</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>屋上</kanji>	
<furigana>おくじょう</furigana>	
<tanos_def>rooftop</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>贈り物</kanji>	
<furigana>おくりもの</furigana>	
<tanos_def>gift</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>送る</kanji>	
<furigana>おくる</furigana>	
<tanos_def>to send</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>遅れる</kanji>	
<furigana>おくれる</furigana>	
<tanos_def>to be late</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>起す</kanji>	
<furigana>おこす</furigana>	
<tanos_def>to wake</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>行う</kanji>	
<furigana>おこなう</furigana>	
<tanos_def>to do</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>怒る</kanji>	
<furigana>おこる</furigana>	
<tanos_def>to get angry, to be angry</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>押し入れ</kanji>	
<furigana>おしいれ</furigana>	
<tanos_def>closet</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お嬢さん</kanji>	
<furigana>おじょうさん</furigana>	
<tanos_def>young lady</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お宅</kanji>	
<furigana>おたく</furigana>	
<tanos_def>(polite) your house</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>落る</kanji>	
<furigana>おちる</furigana>	
<tanos_def>to fall or drop</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>おっしゃる</furigana>	
<tanos_def>(respectful) to say</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>夫</kanji>	
<furigana>おっと</furigana>	
<tanos_def>husband</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>おつり</furigana>	
<tanos_def>change from purchase, balance</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>音</kanji>	
<furigana>おと</furigana>	
<tanos_def>sound, note</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>落す</kanji>	
<furigana>おとす</furigana>	
<tanos_def>to drop</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>踊り</kanji>	
<furigana>おどり</furigana>	
<tanos_def>a dance</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>踊る</kanji>	
<furigana>おどる</furigana>	
<tanos_def>to dance</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>驚く</kanji>	
<furigana>おどろく</furigana>	
<tanos_def>to be surprised</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お祭り</kanji>	
<furigana>おまつり</furigana>	
<tanos_def>festival</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お見舞い</kanji>	
<furigana>おみまい</furigana>	
<tanos_def>calling on someone who is ill, enquiry</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お土産</kanji>	
<furigana>おみやげ</furigana>	
<tanos_def>souvenir</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>思い出す</kanji>	
<furigana>おもいだす</furigana>	
<tanos_def>to remember</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>思う</kanji>	
<furigana>おもう</furigana>	
<tanos_def>to think, to feel</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>おもちゃ</furigana>	
<tanos_def>toy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>表</kanji>	
<furigana>おもて</furigana>	
<tanos_def>the front</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>親</kanji>	
<furigana>おや</furigana>	
<tanos_def>parents</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>泳ぎ方</kanji>	
<furigana>およぎかた</furigana>	
<tanos_def>way of swimming</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>下りる</kanji>	
<furigana>おりる</furigana>	
<tanos_def>to get off, to descend</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>折る</kanji>	
<furigana>おる</furigana>	
<tanos_def>to break or to fold</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お礼</kanji>	
<furigana>おれい</furigana>	
<tanos_def>expression of gratitude</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>折れる</kanji>	
<furigana>おれる</furigana>	
<tanos_def>to break or be folded</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>終わり</kanji>	
<furigana>おわり</furigana>	
<tanos_def>the end</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>海岸</kanji>	
<furigana>かいがん</furigana>	
<tanos_def>coast</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>会議</kanji>	
<furigana>かいぎ</furigana>	
<tanos_def>meeting</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>会議室</kanji>	
<furigana>かいぎしつ</furigana>	
<tanos_def>meeting room</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>会場</kanji>	
<furigana>かいじょう</furigana>	
<tanos_def>assembly hall or meeting place</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>会話</kanji>	
<furigana>かいわ</furigana>	
<tanos_def>conversation</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>帰り</kanji>	
<furigana>かえり</furigana>	
<tanos_def>return</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>変える</kanji>	
<furigana>かえる</furigana>	
<tanos_def>to change</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>科学</kanji>	
<furigana>かがく</furigana>	
<tanos_def>science</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>鏡</kanji>	
<furigana>かがみ</furigana>	
<tanos_def>mirror</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>掛ける</kanji>	
<furigana>かける</furigana>	
<tanos_def>to hang something</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>飾る</kanji>	
<furigana>かざる</furigana>	
<tanos_def>to decorate</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>火事</kanji>	
<furigana>かじ</furigana>	
<tanos_def>fire</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>ガス</furigana>	
<tanos_def>gas</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>堅/硬/固い</kanji>	
<furigana>かたい</furigana>	
<tanos_def>hard</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>形</kanji>	
<furigana>かたち</furigana>	
<tanos_def>shape</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>片付ける</kanji>	
<furigana>かたづける</furigana>	
<tanos_def>to tidy up</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>課長</kanji>	
<furigana>かちょう</furigana>	
<tanos_def>section manager</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>勝つ</kanji>	
<furigana>かつ</furigana>	
<tanos_def>to win</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>家内</kanji>	
<furigana>かない</furigana>	
<tanos_def>housewife</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>悲しい</kanji>	
<furigana>かなしい</furigana>	
<tanos_def>sad</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>必ず</kanji>	
<furigana>かならず</furigana>	
<tanos_def>certainly,necessarily</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>お・金持ち</kanji>	
<furigana>かねもち/おかねもち</furigana>	
<tanos_def>rich man</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>彼女</kanji>	
<furigana>かのじょ</furigana>	
<tanos_def>she,girlfriend</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>壁</kanji>	
<furigana>かべ</furigana>	
<tanos_def>wall</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>髪</kanji>	
<furigana>かみ</furigana>	
<tanos_def>hair</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>噛む</kanji>	
<furigana>かむ</furigana>	
<tanos_def>to bite,to chew</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>通う</kanji>	
<furigana>かよう</furigana>	
<tanos_def>to commute</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>彼</kanji>	
<furigana>かれ</furigana>	
<tanos_def>he,boyfriend</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>乾く</kanji>	
<furigana>かわく</furigana>	
<tanos_def>to get dry</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>代わり</kanji>	
<furigana>かわり</furigana>	
<tanos_def>substitute,alternate</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>変わる</kanji>	
<furigana>かわる</furigana>	
<tanos_def>to change</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>考える</kanji>	
<furigana>かんがえる</furigana>	
<tanos_def>to consider</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>関係</kanji>	
<furigana>かんけい</furigana>	
<tanos_def>relationship</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>看護師</kanji>	
<furigana>かんごし</furigana>	
<tanos_def>nurse</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>簡単</kanji>	
<furigana>かんたん</furigana>	
<tanos_def>simple</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>気</kanji>	
<furigana>き</furigana>	
<tanos_def>spirit,mood</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>機会</kanji>	
<furigana>きかい</furigana>	
<tanos_def>opportunity</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>危険</kanji>	
<furigana>きけん</furigana>	
<tanos_def>danger</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>聞こえる</kanji>	
<furigana>きこえる</furigana>	
<tanos_def>to be heard</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>汽車</kanji>	
<furigana>きしゃ</furigana>	
<tanos_def>steam train</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>技術</kanji>	
<furigana>ぎじゅつ</furigana>	
<tanos_def>art,technology,skill</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>季節</kanji>	
<furigana>きせつ</furigana>	
<tanos_def>season</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>規則</kanji>	
<furigana>きそく</furigana>	
<tanos_def>regulations</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>きっと</furigana>	
<tanos_def>surely</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>絹</kanji>	
<furigana>きぬ</furigana>	
<tanos_def>silk</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>厳しい</kanji>	
<furigana>きびしい</furigana>	
<tanos_def>strict</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>気分</kanji>	
<furigana>きぶん</furigana>	
<tanos_def>mood</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>決る</kanji>	
<furigana>きまる</furigana>	
<tanos_def>to be decided</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>君</kanji>	
<furigana>きみ</furigana>	
<tanos_def>(informal) You</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>決める</kanji>	
<furigana>きめる</furigana>	
<tanos_def>to decide</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>気持ち</kanji>	
<furigana>きもち</furigana>	
<tanos_def>feeling,mood</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>着物</kanji>	
<furigana>きもの</furigana>	
<tanos_def>kimono</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>客</kanji>	
<furigana>きゃく</furigana>	
<tanos_def>guest,customer</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>急</kanji>	
<furigana>きゅう</furigana>	
<tanos_def>urgent, steep</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>急行</kanji>	
<furigana>きゅうこう</furigana>	
<tanos_def>speedy, express</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>教育</kanji>	
<furigana>きょういく</furigana>	
<tanos_def>education</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>教会</kanji>	
<furigana>きょうかい</furigana>	
<tanos_def>church</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>競争</kanji>	
<furigana>きょうそう</furigana>	
<tanos_def>competition</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>興味</kanji>	
<furigana>きょうみ</furigana>	
<tanos_def>an interest</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>近所</kanji>	
<furigana>きんじょ</furigana>	
<tanos_def>neighbourhood</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>具合</kanji>	
<furigana>ぐあい</furigana>	
<tanos_def>condition,health</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>空気</kanji>	
<furigana>くうき</furigana>	
<tanos_def>air,atmosphere</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>空港</kanji>	
<furigana>くうこう</furigana>	
<tanos_def>airport</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>草</kanji>	
<furigana>くさ</furigana>	
<tanos_def>grass</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>首</kanji>	
<furigana>くび</furigana>	
<tanos_def>neck</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>雲</kanji>	
<furigana>くも</furigana>	
<tanos_def>cloud</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>比べる</kanji>	
<furigana>くらべる</furigana>	
<tanos_def>to compare</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>くれる</furigana>	
<tanos_def>to give</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>暮れる</kanji>	
<furigana>くれる</furigana>	
<tanos_def>to get dark,to come to an end</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>君</kanji>	
<furigana>くん</furigana>	
<tanos_def>suffix for familiar young male</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>毛</kanji>	
<furigana>け</furigana>	
<tanos_def>hair or fur</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>経済</kanji>	
<furigana>けいざい</furigana>	
<tanos_def>finance,economy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>警察</kanji>	
<furigana>けいさつ</furigana>	
<tanos_def>police</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>景色</kanji>	
<furigana>けしき</furigana>	
<tanos_def>scene,landscape</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>消しゴム</kanji>	
<furigana>けしゴム</furigana>	
<tanos_def>eraser</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>下宿</kanji>	
<furigana>げしゅく</furigana>	
<tanos_def>lodging</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>決して</kanji>	
<furigana>けっして</furigana>	
<tanos_def>never</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>けれど/けれども</furigana>	
<tanos_def>however</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>原因</kanji>	
<furigana>げんいん</furigana>	
<tanos_def>cause,source</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>けんか・する</furigana>	
<tanos_def>to quarrel</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>研究</kanji>	
<furigana>けんきゅう</furigana>	
<tanos_def>research</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>研究室</kanji>	
<furigana>けんきゅうしつ</furigana>	
<tanos_def>study room,laboratory</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>見物</kanji>	
<furigana>けんぶつ</furigana>	
<tanos_def>sightseeing</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>子</kanji>	
<furigana>こ</furigana>	
<tanos_def>child</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji></kanji>	
<furigana>こう</furigana>	
<tanos_def>this way</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>郊外</kanji>	
<furigana>こうがい</furigana>	
<tanos_def>outskirts</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N4</jlpt>
<level></level>
<kanji>講義</kanji>	