<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GKvocab [
<!ELEMENT GKvocab (vocab_entry*)>

<!-- Voabu;ary Entries consist of ...  -->
<!ELEMENT vocab_entry (ent_seq, dict_seq, kanji, furigana, jlpt, level,  pos+,  definition+, misc+, s_inf+ )>

<!ELEMENT ent_seq (#PCDATA)>
	<!-- A unique numeric sequence number for each vocab entry -->

<!ELEMENT kanji (#PCDATA)>
	<!-- The vocabulary entry text containing kanji characters -->

<!ELEMENT furigana (#PCDATA)>
	<!-- Vocabulary entry in furigana -->

<!ELEMENT jlpt (#PCDATA)>
	<!--  JLPT Level N5, N4, N3, N2, N1, N1+ -->

<!ELEMENT level (#PCDATA)>
	<!--  Sublevel within the JLPT level -->

<!ELEMENT pos (#PCDATA)>
	<!--  Part of Speech -->

<!ELEMENT definition (#PCDATA)>
	<!-- Main definition -->

<!ELEMENT misc (#PCDATA)>
	<!-- Helpful notes about hte vocabulary entry-->

<!ELEMENT s_inf (#PCDATA)>
	<!-- Tags to further classify the vocabulary entry -->
]>


<!-- GKvocab created: 2019-2-20 -->
<GKvocab>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5</jlpt>
<level></level>
<kanji>会う</kanji>	
<furigana>あう</furigana>	
<tanos_def>to meet</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>青</kanji>	
<furigana>あお</furigana>	
<tanos_def>blue</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>青い</kanji>	
<furigana>あおい</furigana>	
<tanos_def>blue</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>赤</kanji>	
<furigana>あか</furigana>	
<tanos_def>red</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>赤い</kanji>	
<furigana>あかい</furigana>	
<tanos_def>red</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>明い</kanji>	
<furigana>あかるい</furigana>	
<tanos_def>bright</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>秋</kanji>	
<furigana>あき</furigana>	
<tanos_def>autumn</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>開く</kanji>	
<furigana>あく</furigana>	
<tanos_def>to open,to become open</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>開ける</kanji>	
<furigana>あける</furigana>	
<tanos_def>to open</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>上げる</kanji>	
<furigana>あげる</furigana>	
<tanos_def>to give</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>朝</kanji>	
<furigana>あさ</furigana>	
<tanos_def>morning</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>朝御飯</kanji>	
<furigana>あさごはん</furigana>	
<tanos_def>breakfast</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あさって</furigana>	
<tanos_def>day after tomorrow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>足</kanji>	
<furigana>あし</furigana>	
<tanos_def>foot,leg</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>明日</kanji>	
<furigana>あした</furigana>	
<tanos_def>tomorrow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あそこ</furigana>	
<tanos_def>over there</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>遊ぶ</kanji>	
<furigana>あそぶ</furigana>	
<tanos_def>to play,to make a visit</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>暖かい</kanji>	
<furigana>あたたかい</furigana>	
<tanos_def>warm</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>頭</kanji>	
<furigana>あたま</furigana>	
<tanos_def>head</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>新しい</kanji>	
<furigana>あたらしい</furigana>	
<tanos_def>new</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あちら</furigana>	
<tanos_def>there</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>暑い</kanji>	
<furigana>あつい</furigana>	
<tanos_def>hot</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>熱い</kanji>	
<furigana>あつい</furigana>	
<tanos_def>hot to the touch</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>厚い</kanji>	
<furigana>あつい</furigana>	
<tanos_def>kind, deep, thick</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あっち</furigana>	
<tanos_def>over there</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>後</kanji>	
<furigana>あと</furigana>	
<tanos_def>afterwards</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あなた</furigana>	
<tanos_def>you</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>兄</kanji>	
<furigana>あに</furigana>	
<tanos_def>(humble) older brother</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>姉</kanji>	
<furigana>あね</furigana>	
<tanos_def>(humble) older sister</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あの</furigana>	
<tanos_def>that over there</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あの</furigana>	
<tanos_def>um...</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>アパート</furigana>	
<tanos_def>apartment</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あびる</furigana>	
<tanos_def>to bathe,to shower</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>危ない</kanji>	
<furigana>あぶない</furigana>	
<tanos_def>dangerous</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>甘い</kanji>	
<furigana>あまい</furigana>	
<tanos_def>sweet</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あまり</furigana>	
<tanos_def>not very</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>雨</kanji>	
<furigana>あめ</furigana>	
<tanos_def>rain</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>飴</kanji>	
<furigana>あめ</furigana>	
<tanos_def>candy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>洗う</kanji>	
<furigana>あらう</furigana>	
<tanos_def>to wash</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>ある</furigana>	
<tanos_def>to be,to have (used for inanimate objects)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>歩く</kanji>	
<furigana>あるく</furigana>	
<tanos_def>to walk</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>あれ</furigana>	
<tanos_def>that</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いい/よい</furigana>	
<tanos_def>good</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いいえ</furigana>	
<tanos_def>no</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>言う</kanji>	
<furigana>いう</furigana>	
<tanos_def>to say</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>家</kanji>	
<furigana>いえ</furigana>	
<tanos_def>house</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いかが</furigana>	
<tanos_def>how</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>行く</kanji>	
<furigana>いく</furigana>	
<tanos_def>to go</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いくつ</furigana>	
<tanos_def>how many?,how old?</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いくら</furigana>	
<tanos_def>how much?</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>池</kanji>	
<furigana>いけ</furigana>	
<tanos_def>pond</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>医者</kanji>	
<furigana>いしゃ</furigana>	
<tanos_def>medical doctor</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いす</furigana>	
<tanos_def>chair</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>忙しい</kanji>	
<furigana>いそがしい</furigana>	
<tanos_def>busy,irritated</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>痛い</kanji>	
<furigana>いたい</furigana>	
<tanos_def>painful</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>一</kanji>	
<furigana>いち</furigana>	
<tanos_def>one</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>一日</kanji>	
<furigana>いちにち</furigana>	
<tanos_def>(1) one day, (2) first of month</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いちばん</furigana>	
<tanos_def>best,first</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いつ</furigana>	
<tanos_def>when</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>五日</kanji>	
<furigana>いつか</furigana>	
<tanos_def>five days, fifth day</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>一緒</kanji>	
<furigana>いっしょ</furigana>	
<tanos_def>together</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>五つ</kanji>	
<furigana>いつつ</furigana>	
<tanos_def>five</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いつも</furigana>	
<tanos_def>always</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>犬</kanji>	
<furigana>いぬ</furigana>	
<tanos_def>dog</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>今</kanji>	
<furigana>いま</furigana>	
<tanos_def>now</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>意味</kanji>	
<furigana>いみ</furigana>	
<tanos_def>meaning</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>妹</kanji>	
<furigana>いもうと</furigana>	
<tanos_def>(humble) younger sister</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>嫌</kanji>	
<furigana>いや</furigana>	
<tanos_def>unpleasant</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>入口</kanji>	
<furigana>いりぐち</furigana>	
<tanos_def>entrance</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>居る</kanji>	
<furigana>いる</furigana>	
<tanos_def>to be, to have (used for people and animals)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>要る</kanji>	
<furigana>いる</furigana>	
<tanos_def>to need</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>入れる</kanji>	
<furigana>いれる</furigana>	
<tanos_def>to put in</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>色</kanji>	
<furigana>いろ</furigana>	
<tanos_def>colour</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>いろいろ</furigana>	
<tanos_def>various</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>上</kanji>	
<furigana>うえ</furigana>	
<tanos_def>on top of</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>後ろ</kanji>	
<furigana>うしろ</furigana>	
<tanos_def>behind</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>薄い</kanji>	
<furigana>うすい</furigana>	
<tanos_def>thin,weak</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>歌</kanji>	
<furigana>うた</furigana>	
<tanos_def>song</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>歌う</kanji>	
<furigana>うたう</furigana>	
<tanos_def>to sing</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>生まれる</kanji>	
<furigana>うまれる</furigana>	
<tanos_def>to be born</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>海</kanji>	
<furigana>うみ</furigana>	
<tanos_def>sea</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>売る</kanji>	
<furigana>うる</furigana>	
<tanos_def>to sell</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>煩い</kanji>	
<furigana>うるさい</furigana>	
<tanos_def>noisy,annoying</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>上着</kanji>	
<furigana>うわぎ</furigana>	
<tanos_def>jacket</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>絵</kanji>	
<furigana>え</furigana>	
<tanos_def>picture</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>映画</kanji>	
<furigana>えいが</furigana>	
<tanos_def>movie</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>映画館</kanji>	
<furigana>えいがかん</furigana>	
<tanos_def>cinema</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>英語</kanji>	
<furigana>えいご</furigana>	
<tanos_def>English language</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>ええ</furigana>	
<tanos_def>yes</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>駅</kanji>	
<furigana>えき</furigana>	
<tanos_def>station</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>エレベーター</furigana>	
<tanos_def>elevator</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>鉛筆</kanji>	
<furigana>えんぴつ</furigana>	
<tanos_def>pencil</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>おいしい</furigana>	
<tanos_def>delicious</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>多い</kanji>	
<furigana>おおい</furigana>	
<tanos_def>many</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>大きい</kanji>	
<furigana>おおきい</furigana>	
<tanos_def>big</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>大きな</kanji>	
<furigana>おおきな</furigana>	
<tanos_def>big</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>大勢</kanji>	
<furigana>おおぜい</furigana>	
<tanos_def>great number of people</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お母さん</kanji>	
<furigana>おかあさん</furigana>	
<tanos_def>(honorable) mother</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お菓子</kanji>	
<furigana>おかし</furigana>	
<tanos_def>sweets, candy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お金</kanji>	
<furigana>おかね</furigana>	
<tanos_def>money</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>起きる</kanji>	
<furigana>おきる</furigana>	
<tanos_def>to get up</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>置く</kanji>	
<furigana>おく</furigana>	
<tanos_def>to put</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>奥さん</kanji>	
<furigana>おくさん</furigana>	
<tanos_def>(honorable) wife</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お酒</kanji>	
<furigana>おさけ</furigana>	
<tanos_def>alcohol, rice wine</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お皿</kanji>	
<furigana>おさら</furigana>	
<tanos_def>plate, dish</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>伯父/叔父</kanji>	
<furigana>おじいさん</furigana>	
<tanos_def>grandfather,male senior citizen</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>教える</kanji>	
<furigana>おしえる</furigana>	
<tanos_def>to teach,to tell</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>伯父/叔父</kanji>	
<furigana>おじさん</furigana>	
<tanos_def>uncle,middle aged gentleman</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>押す</kanji>	
<furigana>おす</furigana>	
<tanos_def>to push, to stamp something</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>遅い</kanji>	
<furigana>おそい</furigana>	
<tanos_def>late,slow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お茶</kanji>	
<furigana>おちゃ</furigana>	
<tanos_def>green tea</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お手洗い</kanji>	
<furigana>おてあらい</furigana>	
<tanos_def>bathroom</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お父さん</kanji>	
<furigana>おとうさん</furigana>	
<tanos_def>(honorable) father</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>弟</kanji>	
<furigana>おとうと</furigana>	
<tanos_def>younger brother</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>男</kanji>	
<furigana>おとこ</furigana>	
<tanos_def>man</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>男の子</kanji>	
<furigana>おとこのこ</furigana>	
<tanos_def>boy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>一昨日</kanji>	
<furigana>おととい</furigana>	
<tanos_def>day before yesterday</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>一昨年</kanji>	
<furigana>おととし</furigana>	
<tanos_def>year before last</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>大人</kanji>	
<furigana>おとな</furigana>	
<tanos_def>adult</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>おなか</furigana>	
<tanos_def>stomach</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>同じ</kanji>	
<furigana>おなじ</furigana>	
<tanos_def>same</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お兄さん</kanji>	
<furigana>おにいさん</furigana>	
<tanos_def>(honorable) older brother</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お姉さん</kanji>	
<furigana>おねえさん</furigana>	
<tanos_def>(honorable) older sister</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>おばあさん</furigana>	
<tanos_def>grandmother,female senior-citizen</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>伯母さん/叔母さん</kanji>	
<furigana>おばさん</furigana>	
<tanos_def>aunt</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お風呂</kanji>	
<furigana>おふろ</furigana>	
<tanos_def>bath</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>お弁当</kanji>	
<furigana>おべんとう</furigana>	
<tanos_def>boxed lunch</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>覚える</kanji>	
<furigana>おぼえる</furigana>	
<tanos_def>to remember</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>おまわりさん</furigana>	
<tanos_def>friendly term for policeman</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>重い</kanji>	
<furigana>おもい</furigana>	
<tanos_def>heavy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>おもしろい</furigana>	
<tanos_def>interesting</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>泳ぐ</kanji>	
<furigana>およぐ</furigana>	
<tanos_def>to swim</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>降りる</kanji>	
<furigana>おりる</furigana>	
<tanos_def>to get off, to descend</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>終る</kanji>	
<furigana>おわる</furigana>	
<tanos_def>to finish</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>音楽</kanji>	
<furigana>おんがく</furigana>	
<tanos_def>music</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>女</kanji>	
<furigana>おんな</furigana>	
<tanos_def>woman</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>女の子</kanji>	
<furigana>おんなのこ</furigana>	
<tanos_def>girl</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>外国</kanji>	
<furigana>がいこく</furigana>	
<tanos_def>foreign country</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>外国人</kanji>	
<furigana>がいこくじん</furigana>	
<tanos_def>foreigner</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>会社</kanji>	
<furigana>かいしゃ</furigana>	
<tanos_def>company</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>階段</kanji>	
<furigana>かいだん</furigana>	
<tanos_def>stairs</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>買い物</kanji>	
<furigana>かいもの</furigana>	
<tanos_def>shopping</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>買う</kanji>	
<furigana>かう</furigana>	
<tanos_def>to buy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>返す</kanji>	
<furigana>かえす</furigana>	
<tanos_def>to return something</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>帰る</kanji>	
<furigana>かえる</furigana>	
<tanos_def>to go back</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>かかる</furigana>	
<tanos_def>to take time or money</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>かぎ</furigana>	
<tanos_def>key</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>書く</kanji>	
<furigana>かく</furigana>	
<tanos_def>to write</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>学生</kanji>	
<furigana>がくせい</furigana>	
<tanos_def>student</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>かける</furigana>	
<tanos_def>to call by phone</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>傘</kanji>	
<furigana>かさ</furigana>	
<tanos_def>umbrella</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>貸す</kanji>	
<furigana>かす</furigana>	
<tanos_def>to lend</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>風</kanji>	
<furigana>かぜ</furigana>	
<tanos_def>wind</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>風邪</kanji>	
<furigana>かぜ</furigana>	
<tanos_def>a cold</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>家族</kanji>	
<furigana>かぞく</furigana>	
<tanos_def>family</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>方</kanji>	
<furigana>かた</furigana>	
<tanos_def>person, way of doing</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>学校</kanji>	
<furigana>がっこう</furigana>	
<tanos_def>school</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>カップ</furigana>	
<tanos_def>cup</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>家庭</kanji>	
<furigana>かてい</furigana>	
<tanos_def>household</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>角</kanji>	
<furigana>かど</furigana>	
<tanos_def>a corner</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>かばん</furigana>	
<tanos_def>bag,basket</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>花瓶</kanji>	
<furigana>かびん</furigana>	
<tanos_def>a vase</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>紙</kanji>	
<furigana>かみ</furigana>	
<tanos_def>paper</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>カメラ</furigana>	
<tanos_def>camera</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>火曜日</kanji>	
<furigana>かようび</furigana>	
<tanos_def>Tuesday</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>辛い</kanji>	
<furigana>からい</furigana>	
<tanos_def>spicy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>体</kanji>	
<furigana>からだ</furigana>	
<tanos_def>body</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>借りる</kanji>	
<furigana>かりる</furigana>	
<tanos_def>to borrow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>軽い</kanji>	
<furigana>かるい</furigana>	
<tanos_def>light</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>カレー</furigana>	
<tanos_def>curry</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>カレンダー</furigana>	
<tanos_def>calendar</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>川/河</kanji>	
<furigana>かわ</furigana>	
<tanos_def>river</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>NONE</kanji>	
<furigana>かわいい</furigana>	
<tanos_def>cute</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>漢字</kanji>	
<furigana>かんじ</furigana>	
<tanos_def>Chinese character</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>木</kanji>	
<furigana>き</furigana>	
<tanos_def>tree,wood</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>黄色</kanji>	
<furigana>きいろ</furigana>	
<tanos_def>yellow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>黄色い</kanji>	
<furigana>きいろい</furigana>	
<tanos_def>yellow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>消える</kanji>	
<furigana>きえる</furigana>	
<tanos_def>to disappear</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq></ent_seq>
<jlpt>N5></jlpt>
<level></level>
<kanji>聞く</kanji>	