<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GKvocab [
<!ELEMENT GKvocab (vocab_entry*)>

<!-- Voabu;ary Entries consist of ...  -->
<!ELEMENT vocab_entry (ent_seq, dict_seq, kanji, furigana, jlpt, level,  pos+,  definition+, misc+, s_inf+ )>

<!ELEMENT ent_seq (#PCDATA)>
	<!-- A unique numeric sequence number for each vocab entry -->

<!ELEMENT kanji (#PCDATA)>
	<!-- The vocabulary entry text containing kanji characters -->

<!ELEMENT furigana (#PCDATA)>
	<!-- Vocabulary entry in furigana -->

<!ELEMENT jlpt (#PCDATA)>
	<!--  JLPT Level N5, N4, N3, N2, N1, N1+ -->

<!ELEMENT level (#PCDATA)>
	<!--  Sublevel within the JLPT level -->

<!ELEMENT pos (#PCDATA)>
	<!--  Part of Speech -->

<!ELEMENT definition (#PCDATA)>
	<!-- Main definition -->

<!ELEMENT misc (#PCDATA)>
	<!-- Helpful notes about hte vocabulary entry-->

<!ELEMENT s_inf (#PCDATA)>
	<!-- Tags to further classify the vocabulary entry -->
]>


<!-- GKvocab created: 2019-2-20 -->
<GKvocab>


<vocab_entry>
<ent_seq>A.190903.03.1000</ent_seq>
<kanji>愛</kanji>	
<furigana>あい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>love</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1001</ent_seq>
<kanji>愛情</kanji>
<furigana>あいじょう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>love, affection</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1002</ent_seq>
<kanji>合図</kanji>
<furigana>あいず</furigana>	
<jlpt>N3</jlpt>
<tanos_def>sign, signal</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1003</ent_seq>
<kanji>愛</kanji>
<furigana>あいする</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to love</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1004</ent_seq>
<kanji>相手</kanji>
<furigana>あいて</furigana>	
<jlpt>N3</jlpt>
<tanos_def>companion, partner, company</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1005</ent_seq>
<kanji></kanji>
<furigana>あいにく</furigana>	
<jlpt>N3</jlpt>
<tanos_def>unfortunately, Sorry, but....</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1006</ent_seq>
<kanji>明</kanji>
<furigana>あかり</furigana>	
<jlpt>N3</jlpt>
<tanos_def>lamplight, light (in general),brightness</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1007</ent_seq>
<kanji>空</kanji>
<furigana>あき</furigana>	
<jlpt>N3</jlpt>
<tanos_def>room, time to spare, emptiness</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1008</ent_seq>
<kanji>明</kanji>
<furigana>あきらか</furigana>	
<jlpt>N3</jlpt>
<tanos_def>obvious, evident, clear</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1009</ent_seq>
<kanji>諦</kanji>
<furigana>あきらめる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to give up, to abandon</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1010</ent_seq>
<kanji>飽</kanji>
<furigana>あきる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to get tired of, to lose interest in, to have enough</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1011</ent_seq>
<kanji>握手</kanji>
<furigana>あくしゅ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>handshake</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1012</ent_seq>
<kanji>悪魔</kanji>
<furigana>あくま</furigana>	
<jlpt>N3</jlpt>
<tanos_def>devil, demon, evil spirit</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1013</ent_seq>
<kanji>明</kanji>
<furigana>あける</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to dawn, to become daylight</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1014</ent_seq>
<kanji>預</kanji>
<furigana>あずける</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to give into custody, to entrust, to deposit</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1015</ent_seq>
<kanji>汗</kanji>
<furigana>あせ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>sweat, perspiration</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1016</ent_seq>
<kanji>与</kanji>
<furigana>あたえる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to give, to present, to award</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1017</ent_seq>
<kanji>暖</kanji>
<furigana>あたたかい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>warm, mild</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1018</ent_seq>
<kanji>辺</kanji>
<furigana>あたり</furigana>	
<jlpt>N3</jlpt>
<tanos_def>vicinity, nearby</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1019</ent_seq>
<kanji>当</kanji>
<furigana>あたる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to be hit, to be successful, to be equivalent to</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1020</ent_seq>
<kanji></kanji>
<furigana>あちこち</furigana>	
<jlpt>N3</jlpt>
<tanos_def>here and there</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1021</ent_seq>
<kanji></kanji>
<furigana>あっ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>Ah!, Oh!</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1022</ent_seq>
<kanji>扱</kanji>
<furigana>あつかう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to handle, to deal with, to treat</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1023</ent_seq>
<kanji>集</kanji>
<furigana>あつまり</furigana>	
<jlpt>N3</jlpt>
<tanos_def>gathering, meeting, assembly, collection</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1024</ent_seq>
<kanji>当</kanji>
<furigana>あてる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to hit, to apply a patch</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1025</ent_seq>
<kanji>跡</kanji>
<furigana>あと</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(1) trace, tracks, mark, sign, (2) remains, ruins, (3) scar</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1026</ent_seq>
<kanji>穴</kanji>
<furigana>あな</furigana>	
<jlpt>N3</jlpt>
<tanos_def>hole</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1027</ent_seq>
<kanji>浴</kanji>
<furigana>あびる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to bathe, to bask in the sun, to shower</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1028</ent_seq>
<kanji>油</kanji>
<furigana>あぶら</furigana>	
<jlpt>N3</jlpt>
<tanos_def>oil</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1029</ent_seq>
<kanji>余</kanji>
<furigana>あまり</furigana>	
<jlpt>N3</jlpt>
<tanos_def>not very,not much</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1030</ent_seq>
<kanji>誤</kanji>
<furigana>あやまり</furigana>	
<jlpt>N3</jlpt>
<tanos_def>error</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1031</ent_seq>
<kanji>粗</kanji>
<furigana>あらい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>Coarse</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1032</ent_seq>
<kanji>嵐</kanji>
<furigana>あらし</furigana>	
<jlpt>N3</jlpt>
<tanos_def>storm, tempest</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1033</ent_seq>
<kanji>新</kanji>
<furigana>あらた</furigana>	
<jlpt>N3</jlpt>
<tanos_def>new, fresh, novel</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1034</ent_seq>
<kanji></kanji>
<furigana>あらゆる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>all, every</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1035</ent_seq>
<kanji>表</kanji>
<furigana>あらわす</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to express, to show, to reveal</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1036</ent_seq>
<kanji>現</kanji>
<furigana>あらわす</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to show, to indicate, to display</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1037</ent_seq>
<kanji>現</kanji>
<furigana>あらわれ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>embodiment, materialization</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1038</ent_seq>
<kanji>現</kanji>
<furigana>あらわれる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(1) to appear, to come in sight, to become visible,(2) to express oneself</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1039</ent_seq>
<kanji></kanji>
<furigana>ありがとう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(conj,exp,int) Thank you</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1040</ent_seq>
<kanji>有</kanji>
<furigana>ある</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to be, to have(used for inanimate objects)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1041</ent_seq>
<kanji>或</kanji>
<furigana>ある</furigana>	
<jlpt>N3</jlpt>
<tanos_def>a certain...,some...</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1042</ent_seq>
<kanji></kanji>
<furigana>あるいは</furigana>	
<jlpt>N3</jlpt>
<tanos_def>or, possibly</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1043</ent_seq>
<kanji>泡</kanji>
<furigana>あわ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>bubble, foam, froth, head on beer</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1044</ent_seq>
<kanji>合</kanji>
<furigana>あわせる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to join together, to be opposite, to face, to unite</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1045</ent_seq>
<kanji>哀</kanji>
<furigana>あわれ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>helpless, pity, sorrow, grief</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1046</ent_seq>
<kanji>案</kanji>
<furigana>あん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>plan, suffix meaning draft</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1047</ent_seq>
<kanji>暗記</kanji>
<furigana>あんき</furigana>	
<jlpt>N3</jlpt>
<tanos_def>memorization, learning by heart</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1048</ent_seq>
<kanji>安定</kanji>
<furigana>あんてい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>stability, equilibrium</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1049</ent_seq>
<kanji>案内</kanji>
<furigana>あんない</furigana>
<jlpt>N3</jlpt>
<tanos_def>・する	information, guidance, leading, to guide</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1050</ent_seq>
<kanji></kanji>
<furigana>あんなに</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to that extent, to that degree</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1051</ent_seq>
<kanji></kanji>
<furigana>あんまり</furigana>	
<jlpt>N3</jlpt>
<tanos_def>not very, not much, remainder, rest</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1052</ent_seq>
<kanji>胃</kanji>
<furigana>い</furigana>	
<jlpt>N3</jlpt>
<tanos_def>stomach</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1053</ent_seq>
<kanji>委員</kanji>
<furigana>いいん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>committee member</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1054</ent_seq>
<kanji>いえ</kanji>
<furigana>いえ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>same as いいえ in spoken</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1055</ent_seq>
<kanji>意外</kanji>
<furigana>いがい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>unexpected, surprising</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1056</ent_seq>
<kanji>息</kanji>
<furigana>いき</furigana>	
<jlpt>N3</jlpt>
<tanos_def>breath, tone</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1057</ent_seq>
<kanji>行</kanji>
<furigana>いき</furigana>/
<jlpt>N3</jlpt>
<tanos_def>ゆき	going,</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1058</ent_seq>
<kanji>勢</kanji>
<furigana>いきおい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>force, vigour, energy, spirit</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1059</ent_seq>
<kanji>生</kanji>
<furigana>物</furigana>	
<jlpt>N3</jlpt>
<tanos_def>いきもの	living thing, animal</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1060</ent_seq>
<kanji>幾</kanji>
<furigana>いくつ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>how many?, how old?</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1061</ent_seq>
<kanji>幾</kanji>
<furigana>いくら</furigana>	
<jlpt>N3</jlpt>
<tanos_def>how much?,</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1062</ent_seq>
<kanji></kanji>
<furigana>いけない</furigana>	
<jlpt>N3</jlpt>
<tanos_def>must not do, bad, wrong, not good</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1063</ent_seq>
<kanji>医師</kanji>
<furigana>いし</furigana>	
<jlpt>N3</jlpt>
<tanos_def>doctor, physician</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1064</ent_seq>
<kanji>意思</kanji>
<furigana>いし</furigana>	
<jlpt>N3</jlpt>
<tanos_def>mind, intention</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1065</ent_seq>
<kanji>意志</kanji>
<furigana>いし</furigana>	
<jlpt>N3</jlpt>
<tanos_def>will, volition</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1066</ent_seq>
<kanji>維持</kanji>
<furigana>いじ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>maintenance, preservation</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1067</ent_seq>
<kanji>意識</kanji>
<furigana>いしき</furigana>	
<jlpt>N3</jlpt>
<tanos_def>consciousness, senses</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1068</ent_seq>
<kanji>異常</kanji>
<furigana>いじょう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>strangeness, abnormality, disorder</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1069</ent_seq>
<kanji>椅子</kanji>
<furigana>いす</furigana>	
<jlpt>N3</jlpt>
<tanos_def>chair</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1070</ent_seq>
<kanji>泉</kanji>
<furigana>いずみ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>spring, fountain</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1071</ent_seq>
<kanji></kanji>
<furigana>いずれ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>which, either, one</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1072</ent_seq>
<kanji>以前</kanji>
<furigana>いぜん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>ago since, before, previous</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1073</ent_seq>
<kanji>板</kanji>
<furigana>いた</furigana>	
<jlpt>N3</jlpt>
<tanos_def>board, plank</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1074</ent_seq>
<kanji>偉大</kanji>
<furigana>いだい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>greatness</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1075</ent_seq>
<kanji>抱</kanji>
<furigana>いだく</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to embrace, to hug, to harbour, to entertain</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1076</ent_seq>
<kanji></kanji>
<furigana>いたずら</furigana>	
<jlpt>N3</jlpt>
<tanos_def>tease, prank, trick, practical joke</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1077</ent_seq>
<kanji></kanji>
<furigana>いただきます</furigana>	
<jlpt>N3</jlpt>
<tanos_def>expression of gratitude before meals</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1078</ent_seq>
<kanji>頂</kanji>
<furigana>いただく</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to receive, to take food or drink</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1079</ent_seq>
<kanji>痛</kanji>
<furigana>いたみ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>pain, ache, sore, grief, distress</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1080</ent_seq>
<kanji>至</kanji>
<furigana>いたる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to come, to arrive</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1081</ent_seq>
<kanji>市</kanji>
<furigana>いち</furigana>	
<jlpt>N3</jlpt>
<tanos_def>market, fair</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1082</ent_seq>
<kanji>位置</kanji>
<furigana>いち</furigana>	
<jlpt>N3</jlpt>
<tanos_def>place, situation, position, location</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1083</ent_seq>
<kanji>一時</kanji>
<furigana>いちじ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>moment, time</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1084</ent_seq>
<kanji>一度</kanji>
<furigana>いちどに</furigana>	
<jlpt>N3</jlpt>
<tanos_def>all at once</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1085</ent_seq>
<kanji>市場</kanji>
<furigana>いちば</furigana>	
<jlpt>N3</jlpt>
<tanos_def>market (as a concept)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1086</ent_seq>
<kanji>一番</kanji>
<furigana>いちばん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>best, first, number one</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1087</ent_seq>
<kanji>一家</kanji>
<furigana>いっか</furigana>	
<jlpt>N3</jlpt>
<tanos_def>a house, a home, a family, a household</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1088</ent_seq>
<kanji></kanji>
<furigana>いつか</furigana>	
<jlpt>N3</jlpt>
<tanos_def>sometime, someday, one day</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1089</ent_seq>
<kanji>一種</kanji>
<furigana>いっしゅ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>a species, a kind, a variety</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1090</ent_seq>
<kanji>一瞬</kanji>
<furigana>いっしゅん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>a moment, an instant</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1091</ent_seq>
<kanji>一生</kanji>
<furigana>いっしょう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>whole life, a lifetime, all through life</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1092</ent_seq>
<kanji>一層</kanji>
<furigana>いっそう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>much more, still more, all the more</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1093</ent_seq>
<kanji>一体</kanji>
<furigana>いったい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(1) one object, one body,(2) what on earth?, really?,(3) generally</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1094</ent_seq>
<kanji>一致</kanji>
<furigana>いっち</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(1) coincidence, agreement,(2) conformity</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1095</ent_seq>
<kanji></kanji>
<furigana>いつでも</furigana>	
<jlpt>N3</jlpt>
<tanos_def>any time, always, at all times, never (when used negatively)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1096</ent_seq>
<kanji>一般</kanji>
<furigana>いっぱん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>general, liberal, universal, ordinary, average</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1097</ent_seq>
<kanji>一方</kanji>
<furigana>いっぽう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(1) on the other hand,(2) meanwhile,(3) only, simple, in turn</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1098</ent_seq>
<kanji></kanji>
<furigana>いつまでも</furigana>	
<jlpt>N3</jlpt>
<tanos_def>forever, for good, eternally, as long as one likes, indefinitely</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1099</ent_seq>
<kanji></kanji>
<furigana>いつも</furigana>	
<jlpt>N3</jlpt>
<tanos_def>always, usually, every time, never (when used negatively)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1100</ent_seq>
<kanji>移動</kanji>
<furigana>いどう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>removal, migration, movement</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1101</ent_seq>
<kanji>従兄弟</kanji>
<furigana>いとこ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>male cousin</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1102</ent_seq>
<kanji>稲</kanji>
<furigana>いね</furigana>	
<jlpt>N3</jlpt>
<tanos_def>rice-plant</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1103</ent_seq>
<kanji>居眠</kanji>
<furigana>いねむり</furigana>	
<jlpt>N3</jlpt>
<tanos_def>dozing, nodding off</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1104</ent_seq>
<kanji>命</kanji>
<furigana>いのち</furigana>	
<jlpt>N3</jlpt>
<tanos_def>,life, destiny</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1105</ent_seq>
<kanji>違反</kanji>
<furigana>いはん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>violation of law,transgression, infringement, breach</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1106</ent_seq>
<kanji>衣服</kanji>
<furigana>いふく</furigana>	
<jlpt>N3</jlpt>
<tanos_def>clothes</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1107</ent_seq>
<kanji>居間</kanji>
<furigana>いま</furigana>	
<jlpt>N3</jlpt>
<tanos_def>western style living room</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1108</ent_seq>
<kanji>今</kanji>
<furigana>いまに</furigana>	
<jlpt>N3</jlpt>
<tanos_def>before long, even now</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1109</ent_seq>
<kanji>今</kanji>
<furigana>いまにも</furigana>	
<jlpt>N3</jlpt>
<tanos_def>at any time, soon</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1110</ent_seq>
<kanji>否</kanji>
<furigana>いや</furigana>	
<jlpt>N3</jlpt>
<tanos_def>no, the nose</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1111</ent_seq>
<kanji>以来</kanji>
<furigana>いらい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>since, henceforth</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1112</ent_seq>
<kanji>依頼</kanji>
<furigana>いらい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(1) request, commission, dispatch,(2) dependence, trust</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1113</ent_seq>
<kanji></kanji>
<furigana>いらいら</furigana>	
<jlpt>N3</jlpt>
<tanos_def>getting nervous, irritation</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1114</ent_seq>
<kanji></kanji>
<furigana>いらっしゃい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>welcome</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1115</ent_seq>
<kanji>医療</kanji>
<furigana>いりょう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>medical care, medical treatment</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1116</ent_seq>
<kanji>岩</kanji>
<furigana>いわ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>rock, crag</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1117</ent_seq>
<kanji>祝</kanji>
<furigana>いわい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>celebration, festival</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1118</ent_seq>
<kanji>祝</kanji>
<furigana>いわう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to congratulate, to celebrate</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1119</ent_seq>
<kanji>言</kanji>
<furigana>いわば</furigana>	
<jlpt>N3</jlpt>
<tanos_def>so to speak</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1120</ent_seq>
<kanji></kanji>
<furigana>いわゆる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>the so-called, so to speak</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1121</ent_seq>
<kanji>印刷</kanji>
<furigana>いんさつ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>printing</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1122</ent_seq>
<kanji>印象</kanji>
<furigana>いんしょう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>impression</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1123</ent_seq>
<kanji>引退</kanji>
<furigana>いんたい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>retire</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1124</ent_seq>
<kanji>引用</kanji>
<furigana>いんよう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>quotation, citation</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1125</ent_seq>
<kanji>魚</kanji>
<furigana>うお</furigana>	
<jlpt>N3</jlpt>
<tanos_def>fish</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1126</ent_seq>
<kanji></kanji>
<furigana>うがい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>gargle, rinse mouth</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1127</ent_seq>
<kanji>伺</kanji>
<furigana>うかがう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to visit, to ask, to inquire</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1128</ent_seq>
<kanji>受</kanji>
<furigana>取</furigana>
<jlpt>N3</jlpt>
<tanos_def>る	うけとる	to receive, to get, to accept, to take</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1129</ent_seq>
<kanji>動</kanji>
<furigana>うごかす</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to move, to shift</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1130</ent_seq>
<kanji>兎</kanji>
<furigana>うさぎ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>rabbit, hare</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1131</ent_seq>
<kanji>牛</kanji>
<furigana>うし</furigana>	
<jlpt>N3</jlpt>
<tanos_def>cattle, cow</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1132</ent_seq>
<kanji>失</kanji>
<furigana>うしなう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to lose, to part with</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1133</ent_seq>
<kanji>後</kanji>
<furigana>うしろ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>afterwards, since then, in the future, behind</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1134</ent_seq>
<kanji>嘘</kanji>
<furigana>うそ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>lie, falsehood, incorrect fact, inappropriate</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1135</ent_seq>
<kanji>疑</kanji>
<furigana>うたがう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to doubt, to distrust, to be suspicious of, to suspect</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1136</ent_seq>
<kanji>内</kanji>
<furigana>うち</furigana>	
<jlpt>N3</jlpt>
<tanos_def>inside</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1137</ent_seq>
<kanji>宇宙</kanji>
<furigana>うちゅう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>universe, cosmos, space</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1138</ent_seq>
<kanji>撃</kanji>
<furigana>うつ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to attack, to defeat, to destroy</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1139</ent_seq>
<kanji>移</kanji>
<furigana>うつす</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to remove, to transfer, to infect</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1140</ent_seq>
<kanji>訴</kanji>
<furigana>うったえる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to sue a person,to resort to, to appeal to</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1141</ent_seq>
<kanji></kanji>
<furigana>うなる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to groan, to moan</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1142</ent_seq>
<kanji>奪</kanji>
<furigana>うばう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to snatch away</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1143</ent_seq>
<kanji>馬</kanji>
<furigana>うま</furigana>	
<jlpt>N3</jlpt>
<tanos_def>(1) horse,(2) promoted bishop (shogi)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1144</ent_seq>
<kanji>うまい</kanji>
<furigana>うまい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>be good at, delicious </tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1145</ent_seq>
<kanji>生</kanji>
<furigana>うまれ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>birth, birth-place</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1146</ent_seq>
<kanji>梅</kanji>
<furigana>うめ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>plum, plum-tree, lowest (of a three-tier ranking system)</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1147</ent_seq>
<kanji>裏切</kanji>
<furigana>うらぎる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to betray, to turn traitor to, to double-cross</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1148</ent_seq>
<kanji>得</kanji>
<furigana>うる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to get, to gain, to win</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1149</ent_seq>
<kanji>嬉</kanji>
<furigana>うれしい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>happy, glad, pleasant</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1150</ent_seq>
<kanji>売</kanji>
<furigana>うれる</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to be sold</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1151</ent_seq>
<kanji>噂</kanji>
<furigana>うわさ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>rumour, report, gossip, common talk</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1152</ent_seq>
<kanji>運</kanji>
<furigana>うん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>fortune, luck</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1153</ent_seq>
<kanji>運転</kanji>
<furigana>うんてん</furigana>
<jlpt>N3</jlpt>
<tanos_def>・する	operation, motion, driving, to drive</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1154</ent_seq>
<kanji>運動</kanji>
<furigana>うんどう</furigana>
<jlpt>N3</jlpt>
<tanos_def>・する	motion, exercise, to exercise</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1155</ent_seq>
<kanji>柄</kanji>
<furigana>え</furigana>	
<jlpt>N3</jlpt>
<tanos_def>handle, grip</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1156</ent_seq>
<kanji>永遠</kanji>
<furigana>えいえん</furigana>	
<jlpt>N3</jlpt>
<tanos_def>eternity, perpetuity, immortality, permanence</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1157</ent_seq>
<kanji>永久</kanji>
<furigana>えいきゅう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>eternity ,perpetuity, immortality</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1158</ent_seq>
<kanji>影響</kanji>
<furigana>えいきょう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>influence, effect</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1159</ent_seq>
<kanji>営業</kanji>
<furigana>えいぎょう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>business, trade, management</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1160</ent_seq>
<kanji>衛星</kanji>
<furigana>えいせい</furigana>	
<jlpt>N3</jlpt>
<tanos_def>satellite</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1161</ent_seq>
<kanji>栄養</kanji>
<furigana>えいよう</furigana>	
<jlpt>N3</jlpt>
<tanos_def>nutrition, nourishment</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1162</ent_seq>
<kanji>笑顔</kanji>
<furigana>えがお</furigana>	
<jlpt>N3</jlpt>
<tanos_def>smiling face</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1163</ent_seq>
<kanji>描</kanji>
<furigana>えがく</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to draw, to paint, to sketch, to depict, to describe</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1164</ent_seq>
<kanji>餌</kanji>
<furigana>えさ</furigana>	
<jlpt>N3</jlpt>
<tanos_def>feed, bait</tanos_def>
</vocab_entry>

<vocab_entry>
<ent_seq>A.190903.03.1165</ent_seq>
<kanji>得</kanji>
<furigana>える</furigana>	
<jlpt>N3</jlpt>
<tanos_def>to get, to gain, to win</tanos_def>